name: movie_night
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  platform_device_id: ^1.0.1
  shared_preferences: ^2.1.0
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http:

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat/static/Montserrat-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Montserrat/static/Montserrat-Light.ttf
        weight: 300
      - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/Montserrat/static/Montserrat-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Montserrat/static/Montserrat-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/Montserrat/static/Montserrat-BoldItalic.ttf
        weight: 700
        style: italic

uses-material-design: true
